'use client';
import { useEffect, useMemo, useState } from 'react';
import { defaultGames, t } from '../../lib/store';
const gkey='marina_worldcup_v3'; const pkey='marina_predictions_v3'; const ADMIN='Ahmed1234';
function read(k, fallback){ if(typeof window==='undefined') return fallback; try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback} }
function write(k,v){ localStorage.setItem(k,JSON.stringify(v)); }
function correctPredictions(game, predictions){ return predictions.filter(p=>p.gameId===game.id && Number(p.homeScore)===Number(game.homeScore) && Number(p.awayScore)===Number(game.awayScore)); }
export default function Admin(){
 const [ok,setOk]=useState(false),[pass,setPass]=useState(''),[games,setGames]=useState(defaultGames),[preds,setPreds]=useState([]),[msg,setMsg]=useState('');
 const [form,setForm]=useState({date:'2026-06-12',kickoff:'22:00',close:'21:30',home:'Mexico',away:'South Africa',homeKu:'مەکسیک',awayKu:'ئەفریقای باشوور',homeAr:'المكسيك',awayAr:'جنوب أفريقيا',homeFlag:'🇲🇽',awayFlag:'🇿🇦'});
 useEffect(()=>{setGames(read(gkey,defaultGames));setPreds(read(pkey,[]));},[]);
 function login(e){e.preventDefault(); if(pass===ADMIN) setOk(true); else setMsg('Wrong password');}
 function saveGames(next){setGames(next);write(gkey,next)}
 function addGame(e){e.preventDefault(); const game={...form,id:Date.now().toString(),status:'open',homeScore:null,awayScore:null,winner:null}; saveGames([...games,game]); setMsg('Game added successfully');}
 function setResult(id,hs,as){ const next=games.map(g=>g.id===id?{...g,homeScore:Number(hs),awayScore:Number(as),status:'closed'}:g); saveGames(next); }
 function chooseWinner(game){ const correct=correctPredictions(game,preds); if(!correct.length){alert('No correct predictions for this game');return;} const pick=correct[Math.floor(Math.random()*correct.length)]; const next=games.map(g=>g.id===game.id?{...g,winner:pick.name,winnerApartment:pick.apartmentCode,winnerDate:new Date().toISOString()}:g); saveGames(next); alert(`Winner selected: ${pick.name}`); }
 function del(id){ if(confirm('Delete this game?')) saveGames(games.filter(g=>g.id!==id)); }
 if(!ok) return <main className="adminWrap"><div className="panel" style={{maxWidth:420,margin:'80px auto'}}><h1>Admin Login</h1><form className="form" onSubmit={login}><input className="input" type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)}/><button className="btn">Login</button>{msg&&<div className="notice error">{msg}</div>}</form></div></main>
 const sorted=[...games].sort((a,b)=>`${a.date} ${a.kickoff}`.localeCompare(`${b.date} ${b.kickoff}`));
 return <main className="adminWrap"><div className="brand" style={{marginBottom:20}}><img className="logo" src="/images/marina-logo.jpeg"/><h1>Marina World Cup Admin</h1></div><div className="adminGrid"><section className="panel"><h2>Add Game</h2><form className="form" onSubmit={addGame}>{['date','kickoff','close','home','away','homeKu','awayKu','homeAr','awayAr','homeFlag','awayFlag'].map(name=><input key={name} className="input" placeholder={name} type={name==='date'?'date':name.includes('kickoff')||name==='close'?'time':'text'} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>) }<button className="btn">Add Game</button>{msg&&<div className="notice">{msg}</div>}</form></section><section className="panel"><h2>Games / Results / Winner</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Date</th><th>Game</th><th>Close</th><th>Score</th><th>Correct</th><th>Winner</th><th></th></tr></thead><tbody>{sorted.map(g=>{const cp=correctPredictions(g,preds); return <tr key={g.id}><td>{g.date}<br/>{g.kickoff}</td><td>{g.homeFlag} {g.home} vs {g.away} {g.awayFlag}</td><td>{g.close}</td><td><Score game={g} onSave={setResult}/></td><td>{cp.length}</td><td>{g.winner||'-'}<br/><button className="btn green" style={{padding:'8px 10px',fontSize:12}} onClick={()=>chooseWinner(g)}>Select Winner</button></td><td><button className="btn secondary" onClick={()=>del(g.id)}>Delete</button></td></tr>})}</tbody></table></div></section></div><section className="panel section"><h2>Predictions</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Apartment</th><th>Game</th><th>Prediction</th></tr></thead><tbody>{preds.map(p=>{const g=games.find(x=>x.id===p.gameId);return <tr key={p.id}><td>{p.name}</td><td>{p.phone}</td><td>{p.apartmentCode}</td><td>{g?`${g.home} vs ${g.away}`:'-'}</td><td>{p.homeScore} - {p.awayScore}</td></tr>})}</tbody></table></div></section></main>
}
function Score({game,onSave}){const [hs,setHs]=useState(game.homeScore??''),[as,setAs]=useState(game.awayScore??'');return <div style={{display:'flex',gap:6,alignItems:'center'}}><input className="input" style={{width:64,padding:8}} type="number" min="0" value={hs} onChange={e=>setHs(e.target.value)}/><span>-</span><input className="input" style={{width:64,padding:8}} type="number" min="0" value={as} onChange={e=>setAs(e.target.value)}/><button className="btn" style={{padding:'8px 10px',fontSize:12}} onClick={()=>onSave(game.id,hs,as)}>Save</button></div>}
