'use client';
import { useEffect, useMemo, useState } from 'react';
import { defaultGames, socials, t } from '../lib/store';

const key = 'marina_worldcup_v3';
const pkey = 'marina_predictions_v3';
function read(k, fallback){ if(typeof window==='undefined') return fallback; try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback} }
function write(k,v){ localStorage.setItem(k,JSON.stringify(v)); window.dispatchEvent(new Event('storage')) }
function teamName(game, lang, side){ const base=side==='home'?'home':'away'; return lang==='ku'?game[base+'Ku']:(lang==='ar'?game[base+'Ar']:game[base]); }
function isClosed(game){ const now = new Date(); const close = new Date(`${game.date}T${game.close}:00`); return now >= close || game.status==='closed'; }
function aptString(a){ return `${a.building}-${a.floor}-${a.apartment}`; }
export default function Home(){
 const [lang,setLang]=useState('ku'); const [games,setGames]=useState(defaultGames); const [predictions,setPredictions]=useState([]); const [selected,setSelected]=useState(null); const [msg,setMsg]=useState('');
 const [form,setForm]=useState({name:'',phone:'',building:'M1',floor:'G',apartment:'1',homeScore:'',awayScore:''}); const tr=t[lang];
 useEffect(()=>{ setGames(read(key,defaultGames)); setPredictions(read(pkey,[])); },[]);
 const sorted=useMemo(()=>[...games].sort((a,b)=>`${a.date} ${a.kickoff}`.localeCompare(`${b.date} ${b.kickoff}`)),[games]);
 const upcoming=sorted.filter(g=>new Date(`${g.date}T${g.kickoff}:00`)>=new Date()).slice(0,3);
 const grouped=sorted.reduce((acc,g)=>{(acc[g.date] ||= []).push(g); return acc;},{});
 const game=selected || upcoming[0] || sorted[0];
 function submit(e){ e.preventDefault(); setMsg(''); if(!game) return; if(isClosed(game)){setMsg(tr.closed);return;} const apt=aptString(form); const exists=predictions.find(p=>p.gameId===game.id && (p.phone.trim()===form.phone.trim() || p.apartmentCode===apt)); if(exists){setMsg(lang==='ku'?'ئەم ژمارەی مۆبایل یان شوقە پێشتر بۆ ئەم یارییە بەشداربووە.':lang==='ar'?'هذا الهاتف أو الشقة شارك سابقاً في هذه المباراة.':'This phone number or apartment already predicted this game.'); return;} if(!form.name||!form.phone){setMsg(lang==='ku'?'تکایە ناو و ژمارەی مۆبایل بنووسە.':lang==='ar'?'يرجى كتابة الاسم ورقم الهاتف.':'Please enter name and phone.');return;} const p={id:Date.now().toString(),gameId:game.id,name:form.name,phone:form.phone,apartmentCode:apt,homeScore:Number(form.homeScore),awayScore:Number(form.awayScore),createdAt:new Date().toISOString()}; const next=[...predictions,p]; setPredictions(next); write(pkey,next); setMsg(lang==='ku'?'پێشبینییەکەت بە سەرکەوتوویی نێردرا.':lang==='ar'?'تم إرسال توقعك بنجاح.':'Your prediction was submitted.'); setForm({...form,homeScore:'',awayScore:''}); }
 return <>
  <header className="topbar"><div className="container nav"><div className="brand"><img className="logo" src="/images/marina-logo.jpeg"/><h1>{tr.title}</h1></div><div className="navlinks"><a href="#games">{tr.allGames}</a><a href="/winners">{tr.winners}</a><a href="/admin">{tr.admin}</a><div className="lang"><button onClick={()=>setLang('ku')}>کوردی</button><button onClick={()=>setLang('en')}>EN</button><button onClick={()=>setLang('ar')}>عربي</button></div></div></div></header>
  <main className="container"><section className="hero"><div className="heroCard"><div><span className="badge">#MarinaWorldCup2026</span><h2>{tr.subtitle}</h2><p>{lang==='ku'?'یارییەک هەڵبژێرە، ئەنجامەکە پێشبینی بکە، و ئەگەر ڕاست بوو لە هەڵبژاردنی براوەکاندا دەبیت.':lang==='ar'?'اختر مباراة، توقع النتيجة، وإذا كان توقعك صحيحاً تدخل في اختيار الفائزين.':'Choose a game, predict the score, and if correct you enter the winner selection.'}</p></div><img className="miniLogo" src="/images/collab-logo.jpeg"/></div></section>
  <section className="grid"><div><div className="panel section"><h3>{tr.upcoming}</h3><div className="gameList">{upcoming.map(g=><GameCard key={g.id} g={g} lang={lang} active={game?.id===g.id} onClick={()=>setSelected(g)} />)}</div></div><div id="games" className="panel section"><h3>{tr.allGames}</h3>{Object.entries(grouped).map(([date,items])=><div key={date}><h3 style={{fontSize:18,color:'#ffb35f'}}>{date}</h3><div className="gameList">{items.map(g=><GameCard key={g.id} g={g} lang={lang} active={game?.id===g.id} onClick={()=>setSelected(g)} />)}</div></div>)}</div></div>
  <aside className="panel section"><h3>{tr.chooseGame}</h3>{game&&<><GameCard g={game} lang={lang} active={true} onClick={()=>{}}/><form className="form" onSubmit={submit}><h3 style={{fontSize:20}}>{tr.register}</h3><input className="input" placeholder={tr.fullName} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder={tr.phone} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}><select value={form.building} onChange={e=>setForm({...form,building:e.target.value})}>{['M1','M2','M3','M4','M5'].map(x=><option key={x}>{x}</option>)}</select><select value={form.floor} onChange={e=>setForm({...form,floor:e.target.value})}>{['G',...Array.from({length:24},(_,i)=>String(i+1))].map(x=><option key={x}>{x}</option>)}</select><select value={form.apartment} onChange={e=>setForm({...form,apartment:e.target.value})}>{['1','2','3','4','5','6'].map(x=><option key={x}>{x}</option>)}</select></div><div className="scoreRow"><div className="team"><span className="flag">{game.homeFlag}</span>{teamName(game,lang,'home')}</div><input className="input" type="number" min="0" required value={form.homeScore} onChange={e=>setForm({...form,homeScore:e.target.value})}/></div><div className="scoreRow"><div className="team"><span className="flag">{game.awayFlag}</span>{teamName(game,lang,'away')}</div><input className="input" type="number" min="0" required value={form.awayScore} onChange={e=>setForm({...form,awayScore:e.target.value})}/></div><button className="btn" disabled={isClosed(game)}>{isClosed(game)?tr.closed:tr.submit}</button>{msg&&<div className={`notice ${msg.includes('پێشتر')||msg.includes('already')||msg.includes('سابق')?'error':''}`}>{msg}</div>}</form></>}</aside></section></main><Footer /> </>
}
function GameCard({g,lang,active,onClick}){ const tr=t[lang]; return <div className={`game ${active?'active':''}`} onClick={onClick}><div className="teams"><div className="team"><span className="flag">{g.homeFlag}</span>{teamName(g,lang,'home')}</div><div className="vs">VS</div><div className="team"><span className="flag">{g.awayFlag}</span>{teamName(g,lang,'away')}</div></div><div className="meta"><span>📅 {g.date}</span><span>🕒 {tr.kickoff}: {g.kickoff}</span><span>⏳ {tr.closes}: {g.close}</span>{g.homeScore!==null&&<span>⚽ {g.homeScore} - {g.awayScore}</span>}</div></div> }
function Footer(){return <footer className="footer"><div className="container"><div className="hashtag">#MarinaWorldCup2026</div><div className="socials"><a href={socials.instagram} target="_blank">📸 Instagram</a><a href={socials.facebook} target="_blank">📘 Facebook</a><a href={socials.tiktok} target="_blank">🎵 TikTok</a></div></div></footer>}
