'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {aptCode,fmt,dayLabel,isClosed,tr} from '../lib/data';
function Socials(){return <div className="socials"><a className="ig" href="https://www.instagram.com/marina__suli?igsh=azhmbWJ2amxhM2xr" target="_blank">⌾ Instagram</a><a className="fb" href="https://www.facebook.com/share/1BZJ3VkDwW/?mibextid=wwXIfr" target="_blank">f Facebook</a><a className="tk" href="https://www.tiktok.com/@marina.suli?_r=1&_t=ZS-978GcpWbCSN" target="_blank">♪ TikTok</a></div>}
export default function Home(){
 const[lang,setLang]=useState('ku'),[state,setState]=useState(null),[selected,setSelected]=useState(''),[msg,setMsg]=useState('');
 const d=tr[lang];
 async function load(){const r=await fetch('/api/state',{cache:'no-store'});const s=await r.json();setState(s);setSelected(x=>x||s.matches?.[0]?.id||'')}
 useEffect(()=>{load()},[]);
 const matches=state?.matches||[]; const match=matches.find(m=>m.id===selected)||matches[0];
 const upcoming=useMemo(()=>matches.filter(m=>new Date(m.kickoff)>=new Date()).slice(0,3),[matches]);
 const predictions=state?.predictions||[];
 const correct=match?predictions.filter(p=>p.match_id===match.id&&p.home_score===match.home_score&&p.away_score===match.away_score):[];
 async function submit(e){e.preventDefault();setMsg('');const f=new FormData(e.currentTarget);const building=f.get('building'),floor=f.get('floor'),apt=f.get('apt');const body={match_id:match.id,name:f.get('name'),phone:f.get('phone'),apartment_code:aptCode(building,floor,apt),home_score:f.get('home_score'),away_score:f.get('away_score')}; if(!body.name||!body.phone||!body.home_score===''||!body.away_score===''){setMsg(d.fill);return} const r=await fetch('/api/predictions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await r.json(); if(!r.ok){setMsg(out.error==='duplicate'?d.duplicate:out.error==='closed'?d.closed:out.error==='badApt'?d.badApt:d.fill);return} e.currentTarget.reset();setMsg(d.sent);load()}
 if(!state)return <div className="loading">Loading...</div>;
 const nm=(m,side)=>lang==='ku'?m[side+'_ku']:(lang==='ar'?(m[side+'_ar']||m[side]):m[side]);
 const byDay=useMemo(()=>matches.reduce((acc,x)=>{const key=new Date(x.kickoff).toDateString();(acc[key] ||= []).push(x);return acc},{}),[matches]);
 return <main className="site" dir={lang==='ku'||lang==='ar'?'rtl':'ltr'}><header className="hero"><div className="heroBg"></div><nav className="top"><Link href="/" className="brand"><img src="/images/marina-logo.jpeg"/><span><b>Marina World Cup 2026</b><small>{d.hashtag}</small></span></Link><div className="menu"><Link href="/">{d.home}</Link><a href="#matches">{d.matches}</a><Link href="/winners">{d.past}</Link><Link href="/admin" className="lock">{d.admin}</Link></div><div className="switch"><button onClick={()=>setLang('ku')} className={lang==='ku'?'on':''}>کوردی</button><button onClick={()=>setLang('en')} className={lang==='en'?'on':''}>EN</button><button onClick={()=>setLang('ar')} className={lang==='ar'?'on':''}>عربي</button></div></nav><div className="heroInner"><div className="copy"><span className="tag">Marina City × Football Nights</span><h1>{d.hero}</h1><p>{d.heroText}</p><div className="heroActions"><a href="#matches" className="primary">{d.select}</a><Link href="/winners" className="ghost">{d.past}</Link></div></div><div className="glass"><h3>{d.upcoming}</h3>{upcoming.map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className="upcoming"><span>{x.home_flag} {nm(x,'home')}</span><b>VS</b><span>{x.away_flag} {nm(x,'away')}</span><small>{fmt(x.kickoff,lang)}</small></button>)}</div></div></header>
 <section id="matches" className="section"><div className="sectionHead"><h2>{d.byDay}</h2><p>{d.chooseGame}</p></div><div className="dayList">{Object.entries(byDay).map(([key,list])=><div className="dayGroup" key={key}><h3>{dayLabel(list[0].kickoff,lang)}</h3><div className="matchGrid">{list.map(x=><button key={x.id} className={'matchCard '+(x.id===match?.id?'active':'')} onClick={()=>setSelected(x.id)}><span>{x.home_flag} {nm(x,'home')}</span><b>VS</b><span>{x.away_flag} {nm(x,'away')}</span><small>{fmt(x.kickoff,lang)}</small></button>)}</div></div>)}</div></section>
 {match&&<section className="section two"><div className="panel highlight"><div className="matchShow"><div><i>{match.home_flag}</i><h2>{nm(match,'home')}</h2></div><strong>VS</strong><div><i>{match.away_flag}</i><h2>{nm(match,'away')}</h2></div></div><div className="timeBoxes"><div><span>{d.kickoff}</span><b>{fmt(match.kickoff,lang)}</b></div><div><span>{d.close}</span><b>{fmt(match.close_at,lang)}</b></div><div><span>Status</span><b className={isClosed(match)?'red':'green'}>{isClosed(match)?d.closed:d.open}</b></div></div>{match.home_score!==null&&<div className="finalScore">{d.score}: {match.home_flag} {match.home_score} - {match.away_score} {match.away_flag}</div>}</div><div className="panel"><h2>{d.predict}</h2><form onSubmit={submit} className="form"><input name="name" placeholder={d.name}/><input name="phone" placeholder={d.phone} inputMode="tel"/><div className="aptRow"><select name="building" defaultValue="M1">{['M1','M2','M3','M4','M5'].map(x=><option key={x}>{x}</option>)}</select><select name="floor" defaultValue="G"><option value="G">Ground</option>{Array.from({length:24},(_,i)=>i+1).map(x=><option key={x}>{x}</option>)}</select><select name="apt" defaultValue="1">{[1,2,3,4,5,6].map(x=><option key={x}>{x}</option>)}</select></div><div className="scorePick"><label><span>{match.home_flag} {nm(match,'home')}</span><small>{d.goals}</small><input name="home_score" type="number" min="0" inputMode="numeric" placeholder="0"/></label><label><span>{match.away_flag} {nm(match,'away')}</span><small>{d.goals}</small><input name="away_score" type="number" min="0" inputMode="numeric" placeholder="0"/></label></div><button disabled={isClosed(match)} className="primary">{isClosed(match)?d.closed:d.send}</button></form>{msg&&<p className="msg">{msg}</p>}</div></section>}
 {match&&<section className="section stats"><div><b>{predictions.filter(p=>p.match_id===match.id).length}</b><span>Predictions</span></div><div><b>{correct.length}</b><span>{d.right}</span></div><div><b>{match.winner_name||'—'}</b><span>{match.winner_name?`${d.winner} · ${match.winner_apartment}`:d.noWinner}</span></div></section>}
 <footer className="footer"><b>{d.hashtag}</b><Socials/><p>Marina City · World Cup 2026</p></footer></main>
}
