export const socialLinks={
 instagram:'https://www.instagram.com/marina__suli?igsh=azhmbWJ2amxhM2xr',
 facebook:'https://www.facebook.com/share/1BZJ3VkDwW/?mibextid=wwXIfr',
 tiktok:'https://www.tiktok.com/@marina.suli?_r=1&_t=ZS-978GcpWbCSN'
};
export const defaultMatches=[
 {id:'sk-cz-2026-06-12-0500',home:'South Korea',away:'Czechia',home_ku:'کۆریای باشوور',away_ku:'چیکیا',home_ar:'كوريا الجنوبية',away_ar:'التشيك',home_flag:'🇰🇷',away_flag:'🇨🇿',kickoff:'2026-06-12T05:00:00+03:00',close_at:'2026-06-12T04:00:00+03:00',home_score:null,away_score:null,winner_name:null,winner_apartment:null},
 {id:'can-bos-2026-06-12-2200',home:'Canada',away:'Bosnia',home_ku:'کەنەدا',away_ku:'بۆسنیا',home_ar:'كندا',away_ar:'البوسنة',home_flag:'🇨🇦',away_flag:'🇧🇦',kickoff:'2026-06-12T22:00:00+03:00',close_at:'2026-06-12T21:00:00+03:00',home_score:null,away_score:null,winner_name:null,winner_apartment:null}
];
export const tr={
 ku:{home:'سەرەکی',matches:'یارییەکان',past:'براوەکانی پێشوو',results:'ئەنجامەکان',admin:'ئێدمین',hero:'پێشبینی بکە و بەشدار بە لە خۆشییەکانی مۆندیال',heroText:'یارییەک هەڵبژێرە، زانیارییەکانت بنووسە، ئەنجامی کۆتایی پێشبینی بکە. ئەگەر پێشبینییەکەت دروست بێت، ناوت دەچێتە لیستی هەڵبژاردن.',today:'یارییەکانی ئەمڕۆ',upcoming:'٣ یاریی داهاتوو',select:'یاری هەڵبژێرە',kickoff:'دەستپێکی یاری',close:'پێشبینی وەردەگیرێت تا',closed:'داخراوە',open:'کراوەیە',predict:'پێشبینی خۆت بنێرە',name:'ناوی تەواو',phone:'ژمارەی مۆبایل',building:'بینای شوقە',floor:'نهۆم',aptNo:'ژمارەی شوقە',send:'پێشبینی بنێرە',goals:'گۆڵ',score:'ئەنجامی کۆتایی',right:'پێشبینییە دروستەکان',winner:'براوە',noWinner:'هێشتا براوە دیاری نەکراوە',sent:'پێشبینییەکەت تۆمارکرا',duplicate:'ئەم ژمارە مۆبایل یان ئەم شوقەیە پێشتر بۆ ئەم یارییە بەکارهاتووە',badApt:'تکایە شوقە بە شێوەی دروست هەڵبژێرە',fill:'تکایە هەموو خانەکان پڕ بکەوە',follow:'فۆڵۆمان بکەن',hashtag:'#MarinaWorldCup2026',allWinners:'براوەکانی پێشوو',noPast:'هێشتا هیچ براوەیەک تۆمار نەکراوە',byDay:'یارییەکان بەپێی ڕۆژ',chooseGame:'یارییەک هەڵبژێرە بۆ پێشبینی'},
 en:{home:'Home',matches:'Matches',past:'Past winners',results:'Results',admin:'Admin',hero:'Predict the match and join the World Cup nights',heroText:'Choose a match, register your details, and predict the final score. Correct predictions enter the selected list.',today:'Today’s matches',upcoming:'Next 3 games',select:'Choose a match',kickoff:'Kickoff',close:'Predictions accepted until',closed:'Closed',open:'Open',predict:'Submit your prediction',name:'Full name',phone:'Phone number',building:'Building',floor:'Floor',aptNo:'Apartment',send:'Submit prediction',goals:'Goals',score:'Final score',right:'Correct predictions',winner:'Winner',noWinner:'No winner selected yet',sent:'Your prediction was saved',duplicate:'This phone number or apartment already predicted this match',badApt:'Please choose a valid apartment',fill:'Please fill all fields',follow:'Follow us',hashtag:'#MarinaWorldCup2026',allWinners:'Past winners',noPast:'No winners yet',byDay:'Matches by day',chooseGame:'Choose a game to predict'},
 ar:{home:'الرئيسية',matches:'المباريات',past:'الفائزون السابقون',results:'النتائج',admin:'الإدارة',hero:'توقع نتيجة المباراة وشارك في أجواء كأس العالم',heroText:'اختر المباراة، سجّل معلوماتك، وتوقع النتيجة النهائية. التوقع الصحيح يدخل قائمة الاختيار.',today:'مباريات اليوم',upcoming:'أقرب ٣ مباريات',select:'اختر مباراة',kickoff:'بداية المباراة',close:'يتم قبول التوقعات حتى',closed:'مغلق',open:'مفتوح',predict:'أرسل توقعك',name:'الاسم الكامل',phone:'رقم الهاتف',building:'المبنى',floor:'الطابق',aptNo:'رقم الشقة',send:'إرسال التوقع',goals:'أهداف',score:'النتيجة النهائية',right:'التوقعات الصحيحة',winner:'الفائز',noWinner:'لم يتم اختيار فائز بعد',sent:'تم حفظ توقعك',duplicate:'هذا الرقم أو هذه الشقة شاركت سابقاً في هذه المباراة',badApt:'يرجى اختيار شقة صحيحة',fill:'يرجى ملء جميع الحقول',follow:'تابعونا',hashtag:'#MarinaWorldCup2026',allWinners:'الفائزون السابقون',noPast:'لا يوجد فائزون بعد',byDay:'المباريات حسب اليوم',chooseGame:'اختر مباراة للتوقع'}
};
export function aptCode(building,floor,apt){return `${building}-${floor}-${apt}`}
export function validApt(code){return /^M[1-5]-(G|[1-9]|1[0-9]|2[0-4])-[1-6]$/.test(code)}
export function fmt(dt,lang='ku'){if(!dt)return '—';const locale=lang==='ku'?'ckb-IQ':lang==='ar'?'ar-IQ':'en-US';return new Date(dt).toLocaleString(locale,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
export function dayLabel(dt,lang='ku'){const locale=lang==='ku'?'ckb-IQ':lang==='ar'?'ar-IQ':'en-US';return new Date(dt).toLocaleDateString(locale,{weekday:'long',month:'long',day:'numeric'})}
export function isClosed(m){return new Date()>new Date(m.close_at)}
